---
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

name: Build

env:
  CGO_ENABLED: 0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Lint using golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run tests
        run: |
          go test -v -cover ./...
